name: Build and Release

on:
  push:
    branches:
      - master  # Watch for updates on the master branch, change if needed
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --add-data "trash_info.py;." main.py

      - name: Set up SSH key for GitHub Actions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Create Git tag and push via SSH
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Create tag only if it doesn't already exist
          git tag v1.0.0 || echo "Tag v1.0.0 already exists"
          
          # Push the tag using SSH
          git push git@github.com:${{ github.repository }} v1.0.0
