name: Build and Release

on:
  push:
    branches:
      - master   # 监听 master 分支的更新，可以改为你自己的分支名
  pull_request:
    branches:
      - master   # 当向 master 分支发起 PR 时，也会触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --add-data "trash_info.py;." main.py

      - name: Create Git tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # 配置 bot 的邮箱
          git config --global user.name "github-actions[bot]"  # 配置 bot 的用户名
          git tag v1.0.0  # 创建一个新标签
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/pinyinjj/filename-clear.git v1.0.0  # 使用 GITHUB_TOKEN 推送标签

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.exe
          tag_name: v1.0.0  # 指定发布标签
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token 进行授权

